/**
 * SafeDoc PDF Report Generator
 * 
 * Generates a client-side structured evidence PDF package using jsPDF.
 * 
 * MANDATORY LEGAL DISCLAIMER FOOTER:
 * "Generated by ShieldHer. This document is a structured evidence record and does not constitute a legal opinion or guarantee of admissibility."
 */

import { jsPDF } from 'jspdf';
import { EvidenceRecord, IncidentCase } from '../../types';

export function generateEvidencePDF(evidence: EvidenceRecord, incidentCase?: IncidentCase | null): jsPDF {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 15;

  // Header Banner
  doc.setFillColor(15, 23, 42); // slate-900
  doc.rect(0, 0, pageWidth, 25, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(20, 184, 166); // teal-500
  doc.text('ShieldHer Digital Safety Toolkit', 14, 12);

  doc.setFontSize(9);
  doc.setTextColor(226, 232, 240);
  doc.text('STRUCTURED EVIDENCE RECORD & COMPLAINT SUMMARY', 14, 18);

  y = 35;

  // 1. Evidence Package Header
  doc.setFontSize(12);
  doc.setTextColor(15, 23, 42);
  doc.text('1. ShieldHer Evidence Summary', 14, y);
  y += 6;

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(51, 65, 85);
  doc.text(`Evidence Record ID: ${evidence.id}`, 14, y);
  doc.text(`Case Reference ID: ${evidence.caseId}`, 110, y);
  y += 5;
  doc.text(`File Name: ${evidence.fileName || 'Original Asset'}`, 14, y);
  doc.text(`Media Type: ${evidence.mediaType}`, 110, y);
  y += 8;

  // 2. Incident Information
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(15, 23, 42);
  doc.text('2. Incident Information', 14, y);
  y += 6;

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text(`Platform: ${incidentCase?.platform || 'Digital Platform'}`, 14, y);
  doc.text(`Incident Date: ${incidentCase?.incidentDate || 'Not specified'}`, 110, y);
  y += 5;
  doc.text(`Source URL: ${incidentCase?.sourceUrl || evidence.sourceUrl || 'Not provided'}`, 14, y);
  y += 8;

  // 3. Evidence Metadata & 4. SHA-256 Hash
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(15, 23, 42);
  doc.text('3. Evidence Metadata & Cryptographic Integrity', 14, y);
  y += 6;

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text(`File Size: ${(evidence.fileSize / 1024).toFixed(1)} KB`, 14, y);
  doc.text(`Dimensions / Format: ${evidence.metadataSummary.width || 'N/A'}x${evidence.metadataSummary.height || 'N/A'}`, 110, y);
  y += 5;

  doc.setFont('courier', 'bold');
  doc.setTextColor(13, 148, 136);
  doc.text(`SHA-256 Hash: ${evidence.sha256}`, 14, y);
  y += 6;

  doc.setFont('helvetica', 'italic');
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  const hashExplain = 'File integrity hash - This hash can help show whether the file changed after hashing. It does not by itself prove that the file was authentic at the moment of capture.';
  doc.text(doc.splitTextToSize(hashExplain, pageWidth - 28), 14, y);
  y += 10;

  // 5. Discovery & Creation Timestamps
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(15, 23, 42);
  doc.text('5. Timestamps (ISO 8601 & Local)', 14, y);
  y += 6;

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(51, 65, 85);
  doc.text(`Discovery Date: ${incidentCase?.discoveryDate || evidence.createdAt}`, 14, y);
  doc.text(`Record Creation: ${evidence.createdAt}`, 110, y);
  y += 8;

  // 7. DeepDetect Screening Result
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(15, 23, 42);
  doc.text('7. DeepDetect Screening Result', 14, y);
  y += 6;

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  const ddLikelihood = evidence.deepDetectResult?.likelihood || 'Not Analyzed';
  const ddConf = evidence.deepDetectResult?.confidenceScore ? `${evidence.deepDetectResult.confidenceScore}%` : 'N/A';
  doc.text(`Manipulation Likelihood: ${ddLikelihood}`, 14, y);
  doc.text(`Confidence Score: ${ddConf}`, 110, y);
  y += 5;
  doc.text(`Processing Location: On-device (Client-side)`, 14, y);
  y += 8;

  // 8. ShieldScan Result
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(15, 23, 42);
  doc.text('8. ShieldScan Perceptual Hash Result', 14, y);
  y += 6;

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  const scanStatus = evidence.shieldScanResult?.status || 'NO_MATCH';
  doc.text(`Perceptual Match Status: ${scanStatus}`, 14, y);
  doc.text(`dHash: ${evidence.shieldScanResult?.perceptualHash || 'N/A'}`, 110, y);
  y += 8;

  // 9. User Notes
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(15, 23, 42);
  doc.text('9. User Incident Notes', 14, y);
  y += 6;

  doc.setFontSize(8.5);
  doc.setFont('helvetica', 'normal');
  const notesText = evidence.notes || incidentCase?.description || 'No additional notes documented.';
  doc.text(doc.splitTextToSize(notesText, pageWidth - 28), 14, y);
  y += 12;

  // 11. Important Limitations & Disclaimers
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(180, 83, 9); // amber-700
  doc.text('11. Important Limitations', 14, y);
  y += 5;

  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(71, 85, 105);
  const limitations = 'Detection results are preliminary screening indicators, not legal proof. This package is structured for Cyber Crime Portal complaint filing and support organization intake.';
  doc.text(doc.splitTextToSize(limitations, pageWidth - 28), 14, y);
  y += 10;

  // 12. Generated Timestamp
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text(`Generated Timestamp: ${new Date().toISOString()} (${new Date().toLocaleString()})`, 14, y);

  // Footer Disclaimer
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  const footerStr = 'Generated by ShieldHer. This document is a structured evidence record and does not constitute a legal opinion or guarantee of admissibility.';
  doc.text(footerStr, pageWidth / 2, 287, { align: 'center' });

  return doc;
}
